### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by thabz** [thabz/Kalliope#488]
```
TypeError: The header content contains invalid characters
    at storeHeader (_http_outgoing.js:436:13)
    at ServerResponse._storeHeader (_http_outgoing.js:350:7)
    at ServerResponse.writeHead (_http_server.js:257:8)
    at redirects.forEach.descr (/home/jec/Sites/kalliope/server.js:159:17)
    at Array.forEach (<anonymous>)
    at Server.createServer (/home/jec/Sites/kalliope/server.js:144:17)
    at emitTwo (events.js:126:13)
    at Server.emit (events.js:214:7)
    at parserOnIncoming (_http_server.js:619:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
```

**Comment by thabz** [comment]
Det er højst sandsynligt en redirect, hvor en indkommende URL omskrives til en ny. Den indkommende URL har indeholdt ulovlige tegn, som overføres til vores nyt URL.

Jeg burde nok have fundet information i accessloggen ... og jeg har mistet tidspunktet nu, men ved kun at jeg opdagede at Kalliope var nede 20/6 2018 kl. 23.55.
